# Generated by Django 3.2.12 on 2024-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospace', '0003_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
    ]
