# Generated by Django 3.2.12 on 2024-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospace', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classes',
            field=models.ManyToManyField(related_name='assignments', to='prospace.Class'),
        ),
    ]
